frr version 9.1
frr defaults datacenter
hostname leaf2
log stdout
!
! leaf2 — AS65012 — uplinks to 3 spines, downlinks to node{1,2,3}.fab1
!
interface lo
 ip address 10.255.2.2/32
!
interface eth1
 ip address 10.2.0.3/31      ! ↔ spine1
interface eth2
 ip address 10.2.0.7/31      ! ↔ spine2
interface eth3
 ip address 10.2.0.11/31     ! ↔ spine3
interface eth4
 ip address 10.3.2.0/31      ! ↔ node1.fab1
interface eth5
 ip address 10.3.2.2/31      ! ↔ node2.fab1
interface eth6
 ip address 10.3.2.4/31      ! ↔ node3.fab1
!
router bgp 65012
 bgp router-id 10.255.2.2
 bgp bestpath as-path multipath-relax
 no bgp ebgp-requires-policy
 neighbor 10.2.0.2 remote-as 65001       ! spine1
 neighbor 10.2.0.6 remote-as 65002       ! spine2
 neighbor 10.2.0.10 remote-as 65003      ! spine3
 neighbor 10.3.2.1 remote-as 65021       ! node1 bird
 neighbor 10.3.2.3 remote-as 65022       ! node2 bird
 neighbor 10.3.2.5 remote-as 65023       ! node3 bird
 !
 address-family ipv4 unicast
  redistribute connected
  maximum-paths 8
  neighbor 10.2.0.2 activate
  neighbor 10.2.0.6 activate
  neighbor 10.2.0.10 activate
  neighbor 10.3.2.1 activate
  neighbor 10.3.2.3 activate
  neighbor 10.3.2.5 activate
 exit-address-family
!
