frr version 9.1
frr defaults datacenter
hostname spine1
log stdout
!
! spine1 — AS65001 — see docs/ADDRESSING.md
!
interface lo
 ip address 10.255.1.1/32
!
interface eth1
 ip address 10.1.1.1/31      ! ↔ tor
interface eth2
 ip address 10.2.0.0/31      ! ↔ leaf1
interface eth3
 ip address 10.2.0.2/31      ! ↔ leaf2
!
router bgp 65001
 bgp router-id 10.255.1.1
 bgp bestpath as-path multipath-relax
 no bgp ebgp-requires-policy
 neighbor 10.1.1.0 remote-as 65000      ! tor
 neighbor 10.2.0.1 remote-as 65011      ! leaf1
 neighbor 10.2.0.3 remote-as 65012      ! leaf2
 !
 address-family ipv4 unicast
  redistribute connected
  maximum-paths 8
  neighbor 10.1.1.0 activate
  neighbor 10.2.0.1 activate
  neighbor 10.2.0.3 activate
 exit-address-family
!
